server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reporte-service
          uri: http://reporte-service
          predicates:
            - Path=/reporte/**
        - id: import-service
          uri: http://import-service
          predicates:
            - Path=/datos/**
            - Path=/entradas/**
        - id: justificativos-service
          uri: http://justificativos-service
          predicates:
            - Path=/justificativos/**
        - id: autorizaciones-service
          uri: http://autorizaciones-service
          predicates:
            - Path=/autorizacion/**