server:
  port: 8030
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: importaciones-service
          uri: lb://importaciones-service
          predicates:
            - Path=/test/**