server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
      routes:
        - id: IMPORTE
          uri: lb://IMPORTE/
          predicates:
            - Path=/datos/**
            - Path=/entradas/**
        - id: reporte-service
          uri: lb://reporte-service
          predicates:
            - Path=/reporte/**
        - id: justificativos-service
          uri: lb://justificativos-service
          predicates:
            - Path=/justificativos/**
        - id: autorizaciones-service
          uri: lb://autorizaciones-service
          predicates:
            - Path=/autorizacion/**