server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/justificativo
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka